// Automatically generated by astro-icon
// 623aa8b720135c1f1af15f21943bf05427e501bda8c6a9aaf746ee8cc0ceb398

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "bingles"
		| "dark"
		| "github"
		| "linkedin"
		| "mastodon";
}