// Automatically generated by astro-icon
// 3e081fd387e84d6baf10ea2002c96290d31d6fed0250b7b841769357bd9d1aa7

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "alpine"
		| "astro"
		| "dark"
		| "django"
		| "docker"
		| "github"
		| "golang"
		| "kafka"
		| "linkedin"
		| "mastodon"
		| "nextjs"
		| "nodejs"
		| "postgres"
		| "react"
		| "redis"
		| "sqlite"
		| "tailwind"
		| "typescript";
}